### ISSUE TITLE
Change notifications UI

### ISSUE THREAD

**Issue by Hid-K** [nujan-io/nujan-ide#1]
I have an issue with popup notifications containing compilation errors. They overlaying some of ui elements.
I think that it will be nice to replace popup notifications with some kind of notifications tray.
I've drew some example as i think it should to look like:
<img width="618" alt="Снимок экрана 2023-06-16 в 23 58 43" src="https://github.com/nujan-io/nujan-ide/assets/61284529/baef143a-c575-4320-a9a4-9a52a67e8810">
All messages should be stored in some local cache until session ends ( page reloaded ).

**Comment by rahulyadav-57** [comment]
We planned to display everything in a log window in the coming milestone and try to reduce the use of notification popups.

**Comment by rahulyadav-57** [comment]
@Hid-K We've developed a logger window that effectively displays all logs in one place.

**Comment by Hid-K** [comment]
Yeah, i see. But is it possible to make console.log displayed in it, while running unit tests?

**Comment by rahulyadav-57** [comment]
Yes, I had similar thoughts as well. Would you mind creating a separate issue for this?

**Comment by devopsavalor** [comment]
All the logs have been moved to the logger window at the bottom of the screen.

**Comment by rahulyadav-57** [comment]
All the logs have been moved to the logger window at the bottom of the screen.
