### ISSUE TITLE
Frozen `Deploying contract . . .` message for an inactive account

### ISSUE THREAD

**Issue by bitspresso** [nujan-io/nujan-ide#12]
Trying to deploy a contract with an account that had not been transitioned to the 'Active' state prompts an message that does not provide any details.

*Possible solution: notify the user of an attempt to deploy from an inactive account.*

![image](https://github.com/nujan-io/nujan-ide/assets/135147216/e96dfdcb-0ec4-45f0-83e6-5e7c2502fc1e)

**Comment by rahulyadav-57** [comment]
@bitspresso I tried with the OpenMask inactive account with some balance in it. I was able to deploy the contract and account automatically became active. Could you help me to replicate the issue?
