### ISSUE TITLE
In cases of connection issues, Nujan doesn't provide meaningful info

### ISSUE THREAD

**Issue by novusnota** [nujan-io/nujan-ide#15]
### Observed behaviour

Build & deploy to Sandbox work as intended (or seem that way), however pressing any of the getter/receiver activation buttons results in a cryptic message in the logs panel:

![image](https://github.com/nujan-io/nujan-ide/assets/68142933/6402a5a9-4bab-40e0-a0a0-34aa0a34a31a)

Where `t[f] is not a function` is caused by pressing on getter buttons, while `Invalid message type` is caused by pressing on receiver buttons.

### Expected behavior or possible solutions

A pop-up or some sort of notification about connection issues. Maybe, just a message in the logs about the disconnect.

**Comment by rahulyadav-57** [comment]
@novusnota Could you help me to reproduce this issue?

**Comment by novusnota** [comment]
@rahulyadav-57 actually, I've just tried to reproduce it by disabling the wifi connection in the middle of the work session and it seems to continue running builds and deployments in Sandbox just fine even offline.

Therefore, I consider this issue resolved (probably in https://github.com/nujan-io/nujan-ide/commit/26f4efd29c31507b7b2b56b90de3f15ea9d3eecb) :)
