### ISSUE TITLE
Introduce automatic save-build-deploy cycle

### ISSUE THREAD

**Issue by novusnota** [nujan-io/nujan-ide#17]
### Observed behaviour

At the moment, one has to manually:
1. Save
2. Press build
3. Press deploy

And all that on each change to the code, which very quickly builds up especially when doing many smaller incremental changes in the course of exploratory-like programming in Tact or FunC.

### Expected behavior or possible solutions

Introduce an automatic save→build→deploy cycle when the target of deployments is Sandbox, which would re-fresh the UI and provide new interface each time.

**Comment by anton-trunov** [comment]
I'd very much enjoy this feature

**Comment by anton-trunov** [comment]
This feature makes my Nujan IDE experience so much better! Thanks @novusnota for suggesting it and @rahulyadav-57 for implementing
