### ISSUE TITLE
Getter and receiver buttons don't refresh

### ISSUE THREAD

**Issue by novusnota** [nujan-io/nujan-ide#18]
### Observed behaviour

Often enough UI buttons get stale even after multiple save→build→deploy buttons and don't appear for new getters and receivers. To resolve this, one has to select and de-select the deployed contract until new buttons appear:

![image](https://github.com/nujan-io/nujan-ide/assets/68142933/100005a2-ea21-4d47-b9ac-7646d21d54b8)

### Expected behavior or possible solutions

Resolving this issue #17 may help, as it suggests making the cycle automatic (or at least semi-automatic) for deploying in the Sandbox.

**Comment by anton-trunov** [comment]
This is a pain point for me as well.
