### ISSUE TITLE
Imports don't work correctly

### ISSUE THREAD

**Issue by Hid-K** [nujan-io/nujan-ide#2]
Imports does not working correctly. I'm importing file from separate folder. When i'm trying to deploy a contract - it fails during compilation with error saying that the compiler did not found a symbol defined in imported file.

My project file structure:
<img width="240" alt="Снимок экрана 2023-06-17 в 00 11 12" src="https://github.com/nujan-io/nujan-ide/assets/61284529/0d03595c-b74c-4c45-8279-ea64ecc59944">

Imports:
<img width="386" alt="Снимок экрана 2023-06-17 в 00 11 51" src="https://github.com/nujan-io/nujan-ide/assets/61284529/8fa89785-e106-429c-8b2f-c05d227a3fbf">

Symbols defined in imported file ( grade-status.fc ):
<img width="459" alt="Снимок экрана 2023-06-17 в 00 12 16" src="https://github.com/nujan-io/nujan-ide/assets/61284529/493654a6-e5ac-4ada-a391-8ee04dadfc21">

Error:
```
Func compilation error: ( function `grade::status::removed` undefined ) cannot generate code for function 
`grade::status::removed`: main.fc:65:9: error: grade::status::removed grade::status::removed(),
```

**Comment by rahulyadav-57** [comment]
Could you share the contract? We will test it and resolve the issue.

**Comment by Hid-K** [comment]
Project sharing does not seems to work, so i'm sending all code in archive.
[TONStudyGrade.zip](https://github.com/nujan-io/nujan-ide/files/11778470/TONStudyGrade.zip)

**Comment by rahulyadav-57** [comment]
I was able to compile the code shared by you.  I hope you are using the stable version https://ide.nujan.io

**Comment by Hid-K** [comment]
yeah. i've been using a wrong version. all works fine now!
