### ISSUE TITLE
IDE should offer to save changes when trying to build an unsaved contract

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#26]
Sometimes I forget to save the file I'm working on and build and deploy the previous version instead of the current one which can be frustrating at times.

**Comment by rahulyadav-57** [comment]
@anton-trunov In case of unsaved changes, it would display a warning. Would that work for you? [Demo](https://nujan-ide-featnotify-for-unsaved-file.vercel.app/)

**Comment by anton-trunov** [comment]
@rahulyadav-57 Yeah, sure, that works. We might revisit it later, but at least it brings your attention to this
