### ISSUE TITLE
Switching between tabs in code editor makes focus shift to the whole browser window

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#28]
This means that when trying to do the 'Select All' command (using a keyboard shortcut like `Cmd-A` on Mac) after a tab switch, all of the browser window text gets selected, instead of just the contents of the code editor window.

**Comment by rahulyadav-57** [comment]
With the latest updates, the editor will automatically focus, ensuring no issues with the 'Select All' functionality.

**Comment by anton-trunov** [comment]
Awesome!
