### ISSUE TITLE
Get sender address for stateinit

### ISSUE THREAD

**Issue by Hid-K** [nujan-io/nujan-ide#3]
How can i get an address which will be used to send an internal message in Sendbox?

**Comment by rahulyadav-57** [comment]
May I know the context for the sender's address?

**Comment by Hid-K** [comment]
Sender's address- is an address of a contract, used in a sandbox to send an internal message.

**Comment by rahulyadav-57** [comment]
I'll figure it out how should I make it usable in a cell and will update you.

**Comment by rahulyadav-57** [comment]
Within the newly introduced logger window, you'll immediately spot the owner's address prominently displayed.

**Comment by rahulyadav-57** [comment]
Now we are displaying the connected wallet address even for the sandbox.

<img width="249" alt="image" src="https://github.com/nujan-io/nujan-ide/assets/14368794/e0657243-ae64-4eec-a2e9-b64b17816a1c">
