### ISSUE TITLE
Display current column 

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#31]
Some error messages are harder to understand because UI lacks the current column information.

**Comment by rahulyadav-57** [comment]
Cursor positions are now displayed in the UI. I hope it will improve the experience.

**Comment by anton-trunov** [comment]
Thanks! Maybe make it a bit more concise? Like 
<img width="93" alt="image" src="https://github.com/nujan-io/nujan-ide/assets/2316541/8d878b9b-888d-44f5-9ca6-83fd5fda1e55">

**Comment by rahulyadav-57** [comment]
Done

**Comment by anton-trunov** [comment]
Perfect!
