### ISSUE TITLE
Implement stricter ESLint rules and add to CI pipeline

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#36]
and fix any issues ESLint finds.

For instance, you might want to reuse the ESLint setup from Tact, especially
- https://github.com/tact-lang/tact/blob/main/.github/workflows/tact.yml
- https://github.com/tact-lang/tact/blob/main/.eslintignore
- https://github.com/tact-lang/tact/blob/main/.eslintrc.cjs
- https://github.com/tact-lang/tact/blob/main/tsconfig.eslint.json

This is the relevant PR: https://github.com/tact-lang/tact/pull/157

**Comment by anton-trunov** [comment]
Any progress here?

**Comment by rahulyadav-57** [comment]
ESLint is already set up in the project; now, I just need to integrate it with the CI pipeline.

**Comment by rahulyadav-57** [comment]
Sure
