### ISSUE TITLE
A better way to input parameters ？

### ISSUE THREAD

**Issue by ichewm** [nujan-io/nujan-ide#5]
![image](https://github.com/nujan-io/nujan-ide/assets/124581466/fb1c1615-9448-4ad8-a9ad-36680c2d1a1a)
**A better way to input parameters ？**
![image](https://github.com/nujan-io/nujan-ide/assets/124581466/7e2af20c-84f5-47e6-8dfe-58e45738298d)

**Comment by vallinayakichidambaram** [comment]
Is this feature implemented? How to pass struct params in function call?

**Comment by rahulyadav-57** [comment]
Not yet. I'll push it by next week.

**Comment by rahulyadav-57** [comment]
It will be tracked in #61
