### ISSUE TITLE
When deploying a contract, if the input value is only one address, the contract cannot be deployed.

### ISSUE THREAD

**Issue by 0x-hewm** [nujan-io/nujan-ide#8]
When the incoming value is an address, the contract can be built but cannot be deployed.

Addresses marked with double quotes and without double quotes cannot be deployed.

![image](https://github.com/nujan-io/nujan-ide/assets/126338339/93efecb9-f425-408d-b054-7b43468856d6)

**Comment by rahulyadav-57** [comment]
This issue has been successfully resolved.
