### ISSUE TITLE
Vim keybindings

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#82]
I'd like to use vim keybinding, hopefully there is a library or plugin that adds this to the Monaco editor

**Comment by rahulyadav-57** [comment]
@anton-trunov Here is the [Staging URL](https://nujan-ide-featureadd-vim-mode-to-editor.vercel.app/). You can switch to `Vim mode` from the `settings` panel. If everything looks good, I'll proceed with the merge.

**Comment by anton-trunov** [comment]
Wow! Looks great!
