### ISSUE TITLE
Vim mode does not activate for existing project

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#88]
The project was created before the IDE had the Vim mode introduced. I switch in the settings Vim mode, but <Esc> does not enter the Normal mode.

**Comment by rahulyadav-57** [comment]
I tested this with a couple of developers who had previously created projects and didn't encounter any issues. Did you experience any error? Could you hard refresh and try again?

**Comment by anton-trunov** [comment]
> Did you experience any error?

No, no error.

> Could you hard refresh and try again?

I restarted my browser (Safari) but it did not help.

What actually helped was creating a new project and then switching back to my original project. Now I can use Vim bindings in both of them

**Comment by anton-trunov** [comment]
I deleted my test project for Vim and know the Vim mode does not activate for my old pre-vim-mode project again

**Comment by rahulyadav-57** [comment]
Strange, I'll look into it.

**Comment by rahulyadav-57** [comment]
`Vim` was not initializing on editor mount, causing it to fail after a refresh or project change. It only worked correctly when changing the settings each time.

**Comment by anton-trunov** [comment]
Thanks! It works now
